config/routes.rb
Rails.application.routes.draw do
    resources :songs 
    resources :users
    resource :session, only: [:new, :create, :destroy]
    root 'welcome#index', as: :home

end

app/models/song.rb
class Song
  include Mongoid::Document
  field :name, type: String
  field :date, type: Date
  field :text, type: String
  field :location, type: String

  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  include Mongoid::Paperclip
  

  field :name, type: String
  field :email, type: String
  field :location, type: String
  field :password_digest, type:String
  

  has_secure_password
  has_many :songs
  has_mongoid_attached_file :image 
  validates_attachment_content_type :image, content_type:["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
		@is_login = true
		if current_user
			redirect_to users_show_path(@user)
		end
	end

	def create
		u = User.where(email: params[:user][:email]).first
		if u && u.authenticate(params[:user][:password])
			session[:user_id] = u.id.to_s
			redirect_to users_path(@user)
		else
			redirect_to new_session_path
		end
	end

	def destroy
		reset_session
		redirect_to home_path
	end
end

app/controllers/songs_controller.rb
class SongsController <ApplicationController

	def index
		my_song_filter = params[:songfilter]
		case my_song_filter
		when "Show All"
			@songs = Song.all
		when "Los Angeles"
			@songs = Song.where(:location => "Los Angeles")
		when "Pasadena"
			@songs = Song.where(:location => "Pasadena")
		when "Santa Monica"
			@songs = Song.where(:location => "Santa Monica")
		else
			@songs = Song.all
		end
	end		

	def show
		@song = Song.find(params[:id])
		# @songs = current_user.song
	end

	def new
		@song = Song.new
	end

	def create
		@song = current_user.songs.new(params.require(:song).permit(:name, :date, :text, :location, :user_id))
		 # @song = Song.new(params.require(:song).permit(:name, :date, :text, :location))
		 if @song.save
		 	redirect_to users_path
		 else
		 	redirect_to create_song_path
		 end
		end

		def edit
			@song = Song.find(params[:id])
		end

		def update
			@song = Song.find(params[:id])
			if @song.update_attributes(params.require(:song).permit(:name, :date, :text, :location, :user_id))
				redirect_to songs_path
			else
				render 'edit'
			end
		end

		def destroy
			@song = Song.find(params[:id])
			@song.destroy
			redirect_to users_path
		end
	end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		# @users = User.all
	end
	
	def new
		@user = User.new
		@is_signup = true
	end
	
	def create
		@user = User.new(params.require(:user).permit(:name, :email, :location, :password, :password_confirmation, :image))
		if @user.save
			session[:user_id] = @user.id.to_s
			redirect_to user_path(@user)
		else
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params.require(:user).permit(:name, :email, :location, :password, :image))
			redirect_to users_path(@user)
		else
			render 'edit'
		end
	end

	def destroy

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@bootstrap = "bootstrap"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar-collapse collapse navbar-fixed-top" role="navigation"> 
  <div class="container-fluid">
    <div class="navbar-header">
      <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="glyphicon glyphicon-align-justify"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-music"> SongMonkey</span>
      </a>
    </div>

    <div class="collapse navbar-collapse"  role="navigation">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li> <%= link_to "Home", users_path %></li>
        <li> <%= link_to "New Song", new_song_path %></li>
        <li><%= link_to 'Logout', session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Sign Up', new_user_path %></li>
        <li><%= link_to 'Login', new_session_path %></li>
      </ul>
      <% end %> 
    </div>
  </div> 
</div>
</nav>



 

app/views/layouts/application.html.erb
 <!DOCTYPE html>
 <html lang="en">
 <head>
 	<meta charset="utf-8">
 	<!-- Set the viewport so this responsive site displays correctly on mobile devices -->
 	<meta name="viewport" content="width=device-width, initial-scale=1">
 	<title>SongMonkey</title>
 	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
 	<%= csrf_meta_tags %>
 </head>

 <body>
<%= render partial: 'layouts/nav'%>
 	<%= yield %>
 </body>
 </html>

app/views/songs/_form.html.erb
<div class="container">
<div class="col-md-4" "col-xs-3">
</div>
<div class="col-md-4" "col-xs-3">
<div class="allform">
	<%= form_for @song, html: {class: 'form'} do |s| %>
	<div class="form-group">
		<%= s.text_field :name, placeholder:"Title", class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= s.text_field :location, placeholder: "City", class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= s.date_field :date, placeholder: "Date", class: 'form-control' %>
	</div>
	<div class="form-group">
		<%= s.text_area :text, placeholder: "What's your Song Today?", class: 'form-control', rows: "8" %>
	</div>
	<br/>
	<div class="button">
		<%= s.submit "Submit", class: 'btn btn-lg btn-default' %>
	</div>
	<% end %>
</div>
</div>
</div>

app/views/songs/edit.html.erb
<div class="mainpage">
	<h1> Edit Song</h1>
	<%= render "form" %>
	<p><%= link_to "Back to all songs", songs_path %></p>
</div>

app/views/songs/index.html.erb
<div class="container">
	<div class="mainpage">
		<div class="row">
								<div class="col-md-12 col-xs-12" id="topbar">
									<h2>Locations</h2>  
									<ul>
										<span class="titles"><li><%= link_to "Show All", songs_path(songfilter:"Show All") %></li></span>
										<span class="titles"><li><%= link_to "Songs in Los Angeles", songs_path(songfilter: "Los Angeles") %></li></span>
										<span class="titles"><li><%= link_to "Songs in Pasadena", songs_path(songfilter: "Pasadena") %></li></span>
										<span class="titles"><li><%= link_to "Songs in Santa Monica", songs_path(songfilter: "Santa Monica") %></li></span>
										<span class="titles"><li><%= link_to "New Song", new_song_path %></li></span>
									</ul>
								</div>
								</div>
		<div class="row">
			<div class="col-md-2 col-xs-0">
			</div>
		<div class="col-md-8 col-xs-12 content" id="leftcol">
			<h1> What are others singing today? </h1>
			<ul class="allsongs">
				<% @songs.each do |s| %>
				<li> <span class="titles">Title</span>&nbsp;&nbsp;<%=s.name %></li>
				<li><span class="titles">Date</span>&nbsp;&nbsp;<%=s.date %></li>
				<li><span class="titles">Place</span>&nbsp;&nbsp;<%=s.location %></li>
				<li><span class="titles">Song</span>&nbsp;&nbsp;<%=s.text %></li>
				<hr><br/><br/>
				<% end %>
			</ul>	
			
			</div>
			<div class="col-md-2 col-xs-0">
			</div>
			</div>	
			<div class="row">	
			<div class="col-md-4 col-xs-12" id="leftcol">
			<h2> Songs in Los Angeles </h2>
			<ul class="allsongs">
				<% @songs.where(:location => "Los Angeles").each do |s| %>
				<li> <span class="titles">Title</span>&nbsp;&nbsp;<%=s.name %></li>
				<li><span class="titles">Date</span>&nbsp;&nbsp;<%=s.date %></li>
				<li><span class="titles">Place</span>&nbsp;&nbsp;<%=s.location %></li>
				<li><span class="titles">Song</span>&nbsp;&nbsp;<%=s.text %></li>
				<hr><br/><br/>
				<% end %>
			</ul>
		</div>
		<div class="col-md-4 col-xs-12" id="leftcol">
			<h2> Songs in Santa Monica </h2>
			<ul class="allsongs">
				<% @songs.where(:location => "Santa Monica").each do |s| %>
				<li> <span class="titles">Title</span>&nbsp;&nbsp;<%=s.name %></li>
				<li><span class="titles">Date</span>&nbsp;&nbsp;<%=s.date %></li>
				<li><span class="titles">Place</span>&nbsp;&nbsp;<%=s.location %></li>
				<li><span class="titles">Song</span>&nbsp;&nbsp;<%=s.text %></li>
				<hr><br/><br/>
				<% end %>
			</ul>
			
		</div>
		<div class="col-md-4 col-xs-12" id="leftcol">
						<h2> Songs in Pasadena </h2>
						<ul class="allsongs">
							<% @songs.where(:location => "Pasadena").each do |s| %>
							<li> <span class="titles">Title</span>&nbsp;&nbsp;<%=s.name %></li>
				<li><span class="titles">Date</span>&nbsp;&nbsp;<%=s.date %></li>
				<li><span class="titles">Place</span>&nbsp;&nbsp;<%=s.location %></li>
				<li><span class="titles">Song</span>&nbsp;&nbsp;<%=s.text %></li>
					<hr id="line"><br/><br/>		
							<% end %>
						</ul>
				
		</div>
		</div>
	</div>
</div>

app/views/songs/new.html.erb
<div class="mainpage">
	<h1> New Song </h1>
	<%= render "form" %>

  <div class="button">
    <%= link_to "All Songs", songs_path, class: 'btn btn-primary btn-large' %>
  </div>
</div>




	

app/views/users/index.html.erb
<div class="mainpage">
	<div class="middle">
		<div class="container-fluid">
			<div class="row">
			<div class="col-md-3 col-sm-0 content" id="leftcol">
				<div class="profile">
				<%= image_tag current_user.image.url, size: "200" %>
				<p><%= current_user.name %></p><br/>
				<p><%= current_user.location %></p>
				</div>					
			</div>
			<div class="col-md-1 col-sm-0 content">
				<br/>
			</div>
			
			<div class="col-md-8 col-sm-12 content" id="rightcol">
				<body>
					<% if current_user %>
					<h2>Whats your song today <%= current_user.name %>?</h2>
						<div class="link"><%= link_to "New Song", new_song_path %></div>
					 
					<br/>
					<br/>
					<h2>What are others singing today?</h2>
					<div class="link"><%= link_to "All Songs", songs_path %></div>
					<br/>
					<% else %>
					<p><%= link_to "Login", new_session_path if !@is_login%></p>
					<% end %>
				</div>
				<div class="row">
					<div class="col-md-2 col-sm-0 content"></div>
					
					<div class="col-md-8 col-md-offset-2 col-sm-12 content" id="middlecol">
					<h2> Your Songs</h2>
					<ul><br/>
						<li><% current_user.songs.all.each do |s| %></li>
						<li><%= s.name %></li>
						<li><%= s.location %></li>
						<li><%= s.text %></li>
						<div class="link"><%= link_to "Delete", s, method: :delete %></div>
						<div class="link"><%= link_to "Edit", edit_song_path(s.id) %><div><br/>
						<% end %><br/>
					</ul>
				</div>
				<div class="col-md-2 col-sm-0 content"></div>					
			</div>
			</div>


			</div>
		</div>
	</div>

app/views/users/new.html.erb
<body>
	<div class="container">
<div class="mainpage">
<div class="row">
	<div class="col-md-4" "col-xs-3">


	</div>
	<div class="col-md-4" "col-xs-3">
	<h1>Sign Up</h1>
	<div class="allform">
		
		<%= form_for @user, html: { class: 'form' } do |f| %>

		<div class="form-group">
			<%= f.text_field :name, placeholder: "Name", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.text_field :email, placeholder: "Email", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.text_field :location, placeholder: "Location", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.password_field :password, placeholder: "Password", class: 'form-control' %>
		</div>


		<div class="form-group">
			<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: 'form-control' %>
		</div>

		<div class="form-group">
			<%= f.file_field :image, placeholder: "Upload a Picture", class: 'form-control' %> 
		</div>
		
		<div class="button">
			<%= f.submit "Submit", class: 'btn btn-lg btn-default' %>
		</div>
		<% end %>
	</div>
</div>
</div>
</div>
</div>
</body>

app/views/users/show.html.erb
<div class="mainpage">
	<div class="middle">
		<div class="container-fluid">
			<div class="row">
			<div class="col-md-3 col-sm-0 content" id="leftcol">
				<div class="profile">
				<%= image_tag current_user.image.url, size: "200" %>
				<p><%= current_user.name %></p><br/>
				<p><%= current_user.location %></p>
				</div>					
			</div>
			<div class="col-md-1 col-sm-0 content">
				<br/>
			</div>
			
			<div class="col-md-8 col-sm-12 content" id="rightcol">
				<body>
					<% if current_user %>
					<h2>Whats your song today <%= current_user.name %>?</h2>
						<div class="link"><%= link_to "New Song", new_song_path %></div>
					 
					<br/>
					<br/>
					<h2>What are others singing today?</h2>
					<div class="link"><%= link_to "All Songs", songs_path %></div>
					<br/>
					<% else %>
					<p><%= link_to "Login", new_session_path if !@is_login%></p>
					<% end %>
				</div>
				<div class="row">
					<div class="col-md-2 col-sm-0 content"></div>
					
					<div class="col-md-8 col-md-offset-2 col-sm-12 content" id="middlecol">
					<h2> Your Songs</h2>
					<ul><br/>
						<li><% current_user.songs.all.each do |s| %></li>
						<li><%= s.name %></li>
						<li><%= s.location %></li>
						<li><%= s.text %></li>
						<div class="link"><%= link_to "Delete", s, method: :delete %></div>
						<div class="link"><%= link_to "Edit", edit_song_path(s.id) %><div><br/>
						<% end %><br/>
					</ul>
				</div>
				<div class="col-md-2 col-sm-0 content"></div>					
			</div>
			</div>


			</div>
		</div>
	</div>

app/views/welcome/index.html.erb
<body class="background">
 		<div class="intro">
  	<h1 >Welcome to SongMonkey</h1>
  	<p>A place to write and save your lyrics. Make a personal profile where you can keep track of your lyrics and share your thoughts. Discover what others around you are singing about. </p>
 	<button type="submit" class="btn btn-lg btn-default"><%= link_to 'Sign Up', new_user_path %></button>
  </div>

</body>